version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: iptv-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
    restart: unless-stopped
    networks:
      - iptv-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: iptv-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - iptv-network

networks:
  iptv-network:
    driver: bridge

volumes:
  backend-data:
  frontend-data: